_parent_: options/base.yaml

arch:
    siren:                                                      # defined for siren
        first_omega: 30
        hidden_omega: 30
        hidden_layers: 3
        hidden_features: 256
        outermost_linear: True
    relu:                                                      # defined for relu
        hidden_layers: 3
        hidden_features: 256
        posenc:
            enabled: False
            L_3D: 8
    gaussian:                                                      # defined for relu
        hidden_layers: 3
        hidden_features: 256
        sigma: 0.09
    wavelet:
        hidden_layers: 3
        hidden_features: 256
        outermost_linear: True
        first_omega: 10
        hidden_omega: 10
        scale: 10


data:                                                        # data options
    dataset: bocc_stanford
    root: data/sdf/shapes
    scene: armadillo                                        # scene_name
    
loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss

optim:                                                      # optimization options
    algo: Adam                                              # Adam/LBFGS
    Adam:
        lr: 1.e-4
        weight_decay: 1.e-8
    ESGD:
        lr: 0.15                
        update: 100
        d_warmup: 50
        damping: 1.e-4
    SGD:
        lr: 1
    Adahessian:
        lr: 0.15
    Shampoo:
        lr: 0.1
    PKFac:
        lr: 0.1
        update_freq: 100


batch_size: 50000                                               # batch size (set to number of patches to consider)
max_iter: 50                                               # train to maximum number of iterations

visdom:                                                     # Visdom options (turned off)

freq:                                                       # periodic actions during training
    scalar: 10                                              # log losses and scalar states (every N iterations)
    val: 10
    ckpt: 100
