_parent_: options/base.yaml

arch:                                                       # architectural options                                                    
    gaussian:
        hidden_layers: 3
        hidden_features: 256
        sigma: 0.05
        sigma_first: 0.05
        sigma_hidden: 0.05
    siren:                                                      # defined for siren
        first_omega: 30
        hidden_omega: 30
        hidden_layers: 3
        hidden_features: 256
        outermost_linear: True
    relu:                                                      # defined for relu
        hidden_layers: 3
        hidden_features: 256
        posenc:
            enabled: False
            L_2D: 8
    wavelet:
        hidden_layers: 3
        hidden_features: 256
        outermost_linear: True
        first_omega: 10
        hidden_omega: 10
        scale: 10

data:                                                       # data options
    image_size: [256,256]                                   # original image size
    batch_size: 512
    div2k_id: 14                                            # [0-14] 
    div2k_mode: "test"                                      # [train, test]

loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss

optim:                                                      # optimization options
    algo: ESGD                                              # Adam/LBFGS
    Adam:
        lr: 1.e-4
        weight_decay: 1.e-8
    ESGD:
        lr: 0.15
        update: 100
        d_warmup: 50
        damping: 1.e-4
    SGD:
        lr: 1
    Shampoo:
        lr: 0.1
    Adahessian:
        lr: 0.15
    PKfac:
        lr: 0.1
        update_freq: 100

batch_size: 1                                               # batch size (set to number of patches to consider)
max_iter: 500                                               # train to maximum number of iterations

visdom:                                                     # Visdom options (turned off)

freq:                                                       # periodic actions during training
    scalar: 10                                              # log losses and scalar states (every N iterations)
    val: 10
    actfn: 1
    weight: 1
    prune: 100
    hess: 10
    jacobian: 10
    
grayscale: False


output_root: output
hessian: 
    full: False
    vecprod: False
    freq: 100
    D_approx: False
    D_exact: False


plot_hvp: False